In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
docs = np.array(['We are the world we are the children',
 'Since the dawn of man is really not that long as every galaxy was formed in less time than it takes to sing this song',
 'There was a fire in the room and all the children burnt to barbeque'])

In [ ]:
bag = vectorizer.fit_transform(docs)
print(vectorizer.get_feature_names())
print(vectorizer.vocabulary_)
print(bag.toarray())

['all', 'and', 'are', 'as', 'barbeque', 'burnt', 'children', 'dawn', 'every', 'fire', 'formed', 'galaxy', 'in', 'is', 'it', 'less', 'long', 'man', 'not', 'of', 'really', 'room', 'since', 'sing', 'song', 'takes', 'than', 'that', 'the', 'there', 'this', 'time', 'to', 'was', 'we', 'world']
{'we': 34, 'are': 2, 'the': 28, 'world': 35, 'children': 6, 'since': 22, 'dawn': 7, 'of': 19, 'man': 17, 'is': 13, 'really': 20, 'not': 18, 'that': 27, 'long': 16, 'as': 3, 'every': 8, 'galaxy': 11, 'was': 33, 'formed': 10, 'in': 12, 'less': 15, 'time': 31, 'than': 26, 'it': 14, 'takes': 25, 'to': 32, 'sing': 23, 'this': 30, 'song': 24, 'there': 29, 'fire': 9, 'room': 21, 'and': 1, 'all': 0, 'burnt': 5, 'barbeque': 4}
[[0 0 2 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 2 1]
 [0 0 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
 [1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 2 1 0 0 1 1 0 0]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)
